version: '3.1'
services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: setdatauser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: n50db
      PGDATA: /pg-data
    ports:
      - "5433:5432"
  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    environment:
      - REDIS_REPLICATION_MODE=master
    container_name: n50-teacher-api-redis
  app:
    build: .
    image: kirigaikabuto/n50-teacher-api
    depends_on:
      - redis
      - database
    ports:
      - "5000:5000"
    environment:
      REDIS_URL: redis:6379
      POSTGRES_USER: setdatauser
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: n50db
    container_name: n50-teacher-api